In [178]:
import pandas as pd
import numpy as np

In [179]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [180]:
df = pd.read_csv('cinemas.csv', index_col=0)
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,Unnamed: 28,war_symb_title,point_symb_title
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,NaN,4,0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,NaN,8,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,NaN,1,0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,NaN,3,0
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,NaN,9,0

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5050 entries, 0 to 5049
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5031 non-null   object
 1   director_name              4946 non-null   object
 2   num_critic_for_reviews     5000 non-null   float64
 3   duration                   5035 non-null   float64
 4   director_facebook_likes    4946 non-null   float64
 5   actor_3_facebook_likes     5027 non-null   float64
 6   actor_2_name               5037 non-null   object
 7   actor_1_facebook_likes     5043 non-null   float64
 8   gross                      4161 non-null   float64
 9   genres                     5050 non-null   object
 10  actor_1_name               5043 non-null   object
 11  movie_title                5050 non-null   object
 12  num_voted_users            5050 non-null   object
 13  cast_total_facebook_likes  5050 non-null   int64
 14  actor_3_name               5027 non-null   object
 15  facenumber_in_poster       5038 non-null   object
 16  plot_keywords              4896 non-null   object
 17  movie_imdb_link            5050 non-null   object
 18  num_user_for_reviews       5029 non-null   object
 19  language                   5036 non-null   object
 20  country                    5045 non-null   object
 21  content_rating             4742 non-null   object
 22  budget                     4557 non-null   float64
 23  title_year                 4942 non-null   float64
 24  actor_2_facebook_likes     5037 non-null   float64
 25  imdb_score                 5050 non-null   float64
 26  aspect_ratio               4721 non-null   float64
 27  movie_facebook_likes       5050 non-null   int64
 28  Unnamed: 28                2 non-null      float64
 29  war_symb_title             5050 non-null   int64
 30  point_symb_title           5050 non-null   int64
dtypes: float64(12), int64(4), object(15)
memory usage: 1.2+ MB

## remove empty columns

In [182]:
df['Unnamed: 28'].value_counts()

Unnamed: 28
0.003      1
424.000    1
Name: count, dtype: int64

In [183]:
df.drop(columns=['Unnamed: 28'], inplace=True)

In [184]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,war_symb_title,point_symb_title
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,4,0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,8,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,1,0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,3,0
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,9,0

## cast columns

In [185]:
cols = ['num_voted_users', 'facenumber_in_poster', 'num_user_for_reviews', 'title_year']
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce').astype('Int64')
categories = ['color', 'language', 'country', 'content_rating']
df[categories] = df[categories].astype('category')

In [186]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5050 entries, 0 to 5049
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5031 non-null   category
 1   director_name              4946 non-null   object
 2   num_critic_for_reviews     5000 non-null   float64
 3   duration                   5035 non-null   float64
 4   director_facebook_likes    4946 non-null   float64
 5   actor_3_facebook_likes     5027 non-null   float64
 6   actor_2_name               5037 non-null   object
 7   actor_1_facebook_likes     5043 non-null   float64
 8   gross                      4161 non-null   float64
 9   genres                     5050 non-null   object
 10  actor_1_name               5043 non-null   object
 11  movie_title                5050 non-null   object
 12  num_voted_users            5049 non-null   Int64
 13  cast_total_facebook_likes  5050 non-null   int64
 14  actor_3_name               5027 non-null   object
 15  facenumber_in_poster       5037 non-null   Int64
 16  plot_keywords              4896 non-null   object
 17  movie_imdb_link            5050 non-null   object
 18  num_user_for_reviews       5028 non-null   Int64
 19  language                   5036 non-null   category
 20  country                    5045 non-null   category
 21  content_rating             4742 non-null   category
 22  budget                     4557 non-null   float64
 23  title_year                 4942 non-null   Int64
 24  actor_2_facebook_likes     5037 non-null   float64
 25  imdb_score                 5050 non-null   float64
 26  aspect_ratio               4721 non-null   float64
 27  movie_facebook_likes       5050 non-null   int64
 28  war_symb_title             5050 non-null   int64
 29  point_symb_title           5050 non-null   int64
dtypes: Int64(4), category(4), float64(10), int64(4), object(8)
memory usage: 1.1+ MB

## fill missing data

In [187]:
df.war_symb_title.value_counts()

war_symb_title
1     1329
2     1288
3      868
0      628
4      476
5      236
6      113
7       53
8       27
9       14
10       9
11       5
14       2
16       1
12       1
Name: count, dtype: int64

In [188]:
df.isna().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        889
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                1
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                154
movie_imdb_link                0
num_user_for_reviews          22
language                      14
country                        5
content_rating               308
budget                       493
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
war_symb_title                 0
point_symb_title               0
dtype: int64

In [189]:
total_missing = df.isna().sum()
percent_missing = (total_missing/df.shape[0]) * 100
percent_missing

color                         0.376238
director_name                 2.059406
num_critic_for_reviews        0.990099
duration                      0.297030
director_facebook_likes       2.059406
actor_3_facebook_likes        0.455446
actor_2_name                  0.257426
actor_1_facebook_likes        0.138614
gross                        17.603960
genres                        0.000000
actor_1_name                  0.138614
movie_title                   0.000000
num_voted_users               0.019802
cast_total_facebook_likes     0.000000
actor_3_name                  0.455446
facenumber_in_poster          0.257426
plot_keywords                 3.049505
movie_imdb_link               0.000000
num_user_for_reviews          0.435644
language                      0.277228
country                       0.099010
content_rating                6.099010
budget                        9.762376
title_year                    2.138614
actor_2_facebook_likes        0.257426
imdb_score                    0.000000
aspect_ratio                  6.514851
movie_facebook_likes          0.000000
war_symb_title                0.000000
point_symb_title              0.000000
dtype: float64

In [190]:
fill_values = {
    'color': df['color'].mode()[0],
    'num_critic_for_reviews': df['num_critic_for_reviews'].mean(),
    'duration': df['duration'].mean(),
    'gross': df['gross'].median(),
    'facenumber_in_poster': df['facenumber_in_poster'].median(),
    'num_voted_users': df['num_voted_users'].median(),
    'director_name': df['director_name'].mode()[0],
    'actor_1_name': df['actor_1_name'].mode()[0],
    'actor_2_name': df['actor_2_name'].mode()[0],
    'actor_3_name': df['actor_3_name'].mode()[0],
    'director_facebook_likes': df['director_facebook_likes'].median(),
    'actor_1_facebook_likes': df['actor_1_facebook_likes'].median(),
    'actor_2_facebook_likes': df['actor_2_facebook_likes'].median(),
    'actor_3_facebook_likes': df['actor_3_facebook_likes'].median(),
    'plot_keywords': df['plot_keywords'].mode()[0],
    'num_user_for_reviews': df['num_user_for_reviews'].median(),
    'language': df['language'].mode()[0],
    'country': df['country'].mode()[0],
    'content_rating': df['content_rating'].mode()[0],
    'budget': df['budget'].median(),
    'title_year': df['title_year'].mode()[0],
    'aspect_ratio': df['aspect_ratio'].median()
}

df = df.fillna(fill_values)

In [191]:
df.isna().sum()

color                        0
director_name                0
num_critic_for_reviews       0
duration                     0
director_facebook_likes      0
actor_3_facebook_likes       0
actor_2_name                 0
actor_1_facebook_likes       0
gross                        0
genres                       0
actor_1_name                 0
movie_title                  0
num_voted_users              0
cast_total_facebook_likes    0
actor_3_name                 0
facenumber_in_poster         0
plot_keywords                0
movie_imdb_link              0
num_user_for_reviews         0
language                     0
country                      0
content_rating               0
budget                       0
title_year                   0
actor_2_facebook_likes       0
imdb_score                   0
aspect_ratio                 0
movie_facebook_likes         0
war_symb_title               0
point_symb_title             0
dtype: int64

In [192]:
df = df.astype({
    'num_voted_users': 'int64',
    'title_year': 'int64'
})

## remove duplicates

In [193]:
df.duplicated().sum()

np.int64(50)

In [194]:
df[df.duplicated()].tail()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,war_symb_title,point_symb_title
4954,Color,David Hewlett,8.0,88.0,686.0,405.0,David Hewlett,847.0,25517500.0,Comedy,Christopher Judge,A Dog's Breakfast,3262,2364,Paul McGillion,2,dog|vegetarian,http://www.imdb.com/title/tt0796314/?ref_=fn_t...,46,English,Canada,R,120000.0,2007,686.0,7.0,1.78,377,4,0
4955,Color,David Hewlett,8.0,88.0,686.0,405.0,David Hewlett,847.0,25517500.0,Comedy,Christopher Judge,A Dog's Breakfast,3262,2364,Paul McGillion,2,dog|vegetarian,http://www.imdb.com/title/tt0796314/?ref_=fn_t...,46,English,Canada,R,120000.0,2007,686.0,7.0,1.78,377,4,0
4956,Color,David Hewlett,8.0,88.0,686.0,405.0,David Hewlett,847.0,25517500.0,Comedy,Christopher Judge,A Dog's Breakfast,3262,2364,Paul McGillion,2,dog|vegetarian,http://www.imdb.com/title/tt0796314/?ref_=fn_t...,46,English,Canada,R,120000.0,2007,686.0,7.0,1.78,377,4,0
4957,Color,David Hewlett,8.0,88.0,686.0,405.0,David Hewlett,847.0,25517500.0,Comedy,Christopher Judge,A Dog's Breakfast,3262,2364,Paul McGillion,2,dog|vegetarian,http://www.imdb.com/title/tt0796314/?ref_=fn_t...,46,English,Canada,R,120000.0,2007,686.0,7.0,1.78,377,4,0
4958,Black and White,George A. Romero,284.0,96.0,0.0,56.0,Duane Jones,125.0,25517500.0,Drama|Horror|Mystery,Judith O'Dea,Night of the Living Dead,87978,403,S. William Hinzman,5,cemetery|farmhouse|radiation|running out of ga...,http://www.imdb.com/title/tt0063350/?ref_=fn_t...,580,English,USA,Unrated,114000.0,1968,108.0,8.0,1.85,0,1,0

In [195]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

## drop odd values

In [196]:
for col in df.select_dtypes(include='category').columns:
    print(f"--- {col} ---")
    print(df[col].value_counts())

--- color ---
color
Color               4792
Black and White      207
Green and Yellow       1
Name: count, dtype: int64
--- language ---
language
English       4676
French          73
Spanish         40
Hindi           28
Mandarin        24
German          19
Japanese        17
Italian         11
Cantonese       11
Russian         11
Portuguese       8
Korean           8
Hebrew           5
Danish           5
Arabic           5
Swedish          5
Norwegian        4
Persian          4
Polish           4
Dutch            4
Thai             3
Chinese          3
Icelandic        2
Indonesian       2
Aboriginal       2
Dari             2
Romanian         2
Zulu             2
Swahili          1
Tamil            1
Telugu           1
Slovenian        1
Urdu             1
Vietnamese       1
8                1
Panjabi          1
Morse            1
Mongolian        1
Maya             1
Kazakh           1
Hungarian        1
Greek            1
Filipino         1
Dzongkha         1
Czech            1
Bosnian          1
Aramaic          1
Kannada          1
Name: count, dtype: int64
--- country ---
country
USA                     3778
UK                       443
France                   154
Canada                   124
Germany                   96
Australia                 55
India                     34
Spain                     33
China                     28
Italy                     23
Japan                     22
Mexico                    17
Hong Kong                 17
New Zealand               15
South Korea               14
Ireland                   12
Russia                    11
Denmark                   11
Norway                     8
South Africa               8
Brazil                     8
Sweden                     6
Poland                     5
Netherlands                5
Thailand                   5
Romania                    4
Israel                     4
Argentina                  4
Belgium                    4
Iran                       4
Switzerland                3
West Germany               3
Iceland                    3
Czech Republic             3
Kyrgyzstan                 2
Hungary                    2
Greece                     2
Taiwan                     2
Indonesia                  1
Cameroon                   1
Colombia                   1
Soviet Union               1
Chile                      1
Bulgaria                   1
Cambodia                   1
Slovakia                   1
Turkey                     1
Bahamas                    1
Aruba                      1
United Arab Emirates       1
Slovenia                   1
Egypt                      1
Dominican Republic         1
English                    1
Philippines                1
Peru                       1
Panama                     1
Pakistan                   1
Official site              1
Finland                    1
Nigeria                    1
Georgia                    1
New Line                   1
Libya                      1
Kenya                      1
Afghanistan                1
Name: count, dtype: int64
--- content_rating ---
content_rating
R            2400
PG-13        1444
PG            698
Not Rated     116
G             112
Unrated        60
Approved       55
TV-14          30
TV-MA          19
TV-PG          13
X              13
TV-G           10
Passed          9
NC-17           7
GP              6
M               5
TV-Y            1
TV-Y7           1
USA             1
Name: count, dtype: int64

In [197]:
df = df.drop(df[df['color'] == 'Green and Yellow'].index)

In [198]:
df.loc[df['title_year'] == 200000]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,war_symb_title,point_symb_title
5038,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,25517500.0,Comedy|Horror|Thriller,Julianna Pitt,Sanctuary,34338,133,1111,1,dog|vegetarian,nudity|party|pirate|swimsuit|three word title,156,8,English,USA,20000000.0,200000,2012.0,98.0,5.4,16,3,0

In [199]:
df = df.drop(df[df['title_year'] == 200000].index)

In [200]:
df.describe(include='all')

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,war_symb_title,point_symb_title
count,4998,4998,4998.000000,4998.000000,4998.000000,4998.000000,4998,4998.000000,4.998000e+03,4998,4998,4998,4.998000e+03,4998.000000,4998,4998.0,4998,4998,4998.0,4998,4998,4998,4.998000e+03,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000
unique,2,2398,NaN,NaN,NaN,NaN,3032,NaN,NaN,915,2097,4916,NaN,NaN,3521,<NA>,4760,4919,<NA>,46,65,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Color,Steven Spielberg,NaN,NaN,NaN,NaN,Morgan Freeman,NaN,NaN,Drama,Robert De Niro,King Kong,NaN,NaN,Ben Mendelsohn,<NA>,dog|vegetarian,http://www.imdb.com/title/tt2638144/?ref_=fn_t...,<NA>,English,USA,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,4791,129,NaN,NaN,NaN,NaN,33,NaN,NaN,235,56,3,NaN,NaN,31,<NA>,153,3,<NA>,4676,3778,2399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,140.023448,107.210608,675.475790,658.759304,NaN,6548.973990,4.433231e+07,NaN,NaN,NaN,8.347018e+04,9676.799720,NaN,1.369148,NaN,NaN,271.530612,NaN,NaN,NaN,3.783102e+07,2002.606042,1640.273709,6.441357,2.226999,7487.369948,2.213685,0.006403
std,NaN,NaN,121.096048,25.214123,2793.900947,2164.143674,NaN,15052.542789,6.234319e+07,NaN,NaN,NaN,1.380866e+05,18165.474048,NaN,2.013658,NaN,NaN,377.053965,NaN,NaN,NaN,1.967115e+08,12.376501,4026.032179,1.124030,1.331101,19290.749088,1.714795,0.089240
min,NaN,NaN,1.000000,7.000000,0.000000,0.000000,NaN,-32.000000,1.620000e+02,NaN,NaN,NaN,5.000000e+00,0.000000,NaN,0.0,NaN,NaN,1.0,NaN,NaN,NaN,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000,0.000000,0.000000
25%,NaN,NaN,50.000000,93.000000,7.000000,134.000000,NaN,612.250000,8.374724e+06,NaN,NaN,NaN,8.560000e+03,1405.500000,NaN,0.0,NaN,NaN,65.0,NaN,NaN,NaN,7.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000,1.000000,0.000000
50%,NaN,NaN,111.000000,103.000000,49.000000,372.000000,NaN,986.000000,2.551750e+07,NaN,NaN,NaN,3.426050e+04,3085.500000,NaN,1.0,NaN,NaN,156.0,NaN,NaN,NaN,2.000000e+07,2006.000000,595.000000,6.600000,2.350000,161.500000,2.000000,0.000000
75%,NaN,NaN,193.000000,118.000000,189.000000,635.000000,NaN,11000.000000,5.137692e+07,NaN,NaN,NaN,9.612075e+04,13740.500000,NaN,2.0,NaN,NaN,323.0,NaN,NaN,NaN,4.000000e+07,2011.000000,912.750000,7.200000,2.350000,3000.000000,3.000000,0.000000
max,NaN,NaN,813.000000,511.000000,23000.000000,100500.000000,NaN,640000.000000,7.605058e+08,NaN,NaN,NaN,1.689764e+06,656730.000000,NaN,43.0,NaN,NaN,5060.0,NaN,NaN,NaN,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000,16.000000,3.000000

## one hot encoding

In [201]:
for col in df.select_dtypes(include='category').columns:
    print(col)

color
language
country
content_rating

In [202]:
df['color'] = df['color'].apply(lambda x: 1 if x == 'Color' else 0)

In [203]:
# one hot encoding
df = pd.get_dummies(df, columns=['language', 'country', 'content_rating'], drop_first=True, dtype=int, sparse=False)

In [204]:
df.iloc[:5, -10:]

,content_rating_R,content_rating_TV-14,content_rating_TV-G,content_rating_TV-MA,content_rating_TV-PG,content_rating_TV-Y,content_rating_TV-Y7,content_rating_USA,content_rating_Unrated,content_rating_X
0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0

## one hot encoding multilabel columns

In [205]:
from sklearn.preprocessing import MultiLabelBinarizer

df['genres_list'] = df['genres'].str.split('|')

mlb = MultiLabelBinarizer(sparse_output=False)
genres_encoded = pd.DataFrame(
    mlb.fit_transform(df['genres_list']),
    columns=[f'genres_{c}' for c in mlb.classes_],
    index=df.index
)

df = df.join(genres_encoded)
df = df.drop(columns=['genres_list'])

df.iloc[:5, -5:]

   genres_Short  genres_Sport  genres_Thriller  genres_War  genres_Western
0             0             0                0           0               0
1             0             0                0           0               0
2             0             0                1           0               0
3             0             0                1           0               0
4             0             0                0           0               0

In [206]:
unique_genres = set(g for sublist in df['genres'].str.split('|') for g in sublist)
print("Number of unique genres:", len(unique_genres))

Number of unique genres: 26

In [207]:
genre_sums = {col: df[col].sum() for col in df.columns if 'genres_' in col}
genre_sums_df = pd.DataFrame(list(genre_sums.items()), columns=['Genre', 'Count']).sort_values('Count', ascending=False).reset_index(drop=True)
genre_sums_df

                 Genre  Count
0         genres_Drama   2571
1        genres_Comedy   1862
2      genres_Thriller   1395
3        genres_Action   1143
4       genres_Romance   1098
5     genres_Adventure    914
6         genres_Crime    883
7        genres_Sci-Fi    612
8       genres_Fantasy    605
9        genres_Horror    555
10       genres_Family    544
11      genres_Mystery    493
12    genres_Biography    292
13    genres_Animation    242
14        genres_Music    212
15          genres_War    211
16      genres_History    205
17        genres_Sport    181
18      genres_Musical    132
19  genres_Documentary    121
20      genres_Western     94
21    genres_Film-Noir      6
22        genres_Short      5
23         genres_News      3
24   genres_Reality-TV      2
25    genres_Game-Show      1

In [208]:
genre_cols = [col for col in df.columns if col.startswith('genres_')]
genre_counts = df[genre_cols].sum()
cols_to_other = genre_counts[genre_counts < 100].index.tolist()
df['genres_Other'] = df[cols_to_other].max(axis=1)
df.drop(columns=cols_to_other, inplace=True)

In [209]:
x = [col for col in list(df.columns) if col.startswith('genres_')]
len(x)

21

In [210]:
genre_sums = {col: df[col].sum() for col in df.columns if 'genres_' in col}
genre_sums_df = pd.DataFrame(list(genre_sums.items()), columns=['Genre', 'Count']).sort_values('Count', ascending=False).reset_index(drop=True)
genre_sums_df

                 Genre  Count
0         genres_Drama   2571
1        genres_Comedy   1862
2      genres_Thriller   1395
3        genres_Action   1143
4       genres_Romance   1098
5     genres_Adventure    914
6         genres_Crime    883
7        genres_Sci-Fi    612
8       genres_Fantasy    605
9        genres_Horror    555
10       genres_Family    544
11      genres_Mystery    493
12    genres_Biography    292
13    genres_Animation    242
14        genres_Music    212
15          genres_War    211
16      genres_History    205
17        genres_Sport    181
18      genres_Musical    132
19  genres_Documentary    121
20        genres_Other    110

In [211]:
from collections import Counter
from itertools import chain

df['keywords_list'] = df['plot_keywords'].fillna('').str.split('|')

# select top 50 keywords
all_keywords = list(chain.from_iterable(df['keywords_list']))
top_keywords = [kw for kw, _ in Counter(all_keywords).most_common(50)]
print("all keywords: ", len(all_keywords))
print("top keywords: ", top_keywords)

# replace rare keywords with "other"
df["keywords_filtered"] = df["keywords_list"].apply(
    lambda x: [kw if kw in top_keywords else "other" for kw in x if kw != '']
)

mlb = MultiLabelBinarizer(sparse_output=False)
keywords_encoded = mlb.fit_transform(df["keywords_filtered"])

keywords_df = pd.DataFrame(
    keywords_encoded,
    columns=[f"keywords_{c}" for c in mlb.classes_],
    index=df.index
)

df = df.join(keywords_df)
df.drop(columns=['keywords_list', 'keywords_filtered', 'plot_keywords', 'genres'], inplace=True)

print(df.iloc[:5, -10:])

all keywords:  24185
top keywords:  ['dog', 'love', 'friend', 'vegetarian', 'murder', 'death', 'police', 'new york city', 'high school', 'alien', 'school', 'boy', 'fbi', 'revenge', 'friendship', 'drugs', 'prison', 'money', 'marriage', 'island', 'female protagonist', 'escape', 'party', 'wedding', 'sex', 'detective', 'serial killer', 'box office flop', 'rescue', 'female nudity', 'teenager', 'lawyer', 'battle', 'best friend', 'hospital', 'christmas', 'secret', 'vomiting', 'train', 'scientist', 'cia', 'singer', 'college', 'hotel', 'future', 'writer', 'fight', 'small town', 'terrorist', 'texas']
   keywords_singer  keywords_small town  keywords_teenager  \
0                0                    0                  0
1                0                    0                  0
2                0                    0                  0
3                0                    0                  0
4                0                    0                  0

   keywords_terrorist  keywords_texas  keywords_train  keywords_vegetarian  \
0                   0               0               0                    0
1                   0               0               0                    0
2                   1               0               0                    0
3                   0               0               0                    0
4                   0               0               0                    1

   keywords_vomiting  keywords_wedding  keywords_writer
0                  0                 0                0
1                  0                 0                0
2                  0                 0                0
3                  0                 0                0
4                  0                 0                0

In [212]:
keywords_stat = [(col, df[col].sum()) for col in df.columns if col.startswith('keywords_')]
keywords_stat_sorted = sorted(keywords_stat, key=lambda x: x[1], reverse=True)
keywords_stat_sorted

[('keywords_other', np.int64(4843)),
 ('keywords_dog', np.int64(208)),
 ('keywords_love', np.int64(194)),
 ('keywords_friend', np.int64(165)),
 ('keywords_murder', np.int64(159)),
 ('keywords_vegetarian', np.int64(159)),
 ('keywords_death', np.int64(132)),
 ('keywords_police', np.int64(126)),
 ('keywords_new york city', np.int64(91)),
 ('keywords_high school', np.int64(89)),
 ('keywords_alien', np.int64(82)),
 ('keywords_school', np.int64(73)),
 ('keywords_boy', np.int64(72)),
 ('keywords_fbi', np.int64(71)),
 ('keywords_revenge', np.int64(70)),
 ('keywords_friendship', np.int64(67)),
 ('keywords_drugs', np.int64(66)),
 ('keywords_prison', np.int64(62)),
 ('keywords_money', np.int64(61)),
 ('keywords_marriage', np.int64(60)),
 ('keywords_female protagonist', np.int64(57)),
 ('keywords_island', np.int64(57)),
 ('keywords_escape', np.int64(56)),
 ('keywords_party', np.int64(55)),
 ('keywords_sex', np.int64(52)),
 ('keywords_wedding', np.int64(52)),
 ('keywords_detective', np.int64(51)),
 ('keywords_serial killer', np.int64(49)),
 ('keywords_box office flop', np.int64(48)),
 ('keywords_female nudity', np.int64(48)),
 ('keywords_rescue', np.int64(48)),
 ('keywords_lawyer', np.int64(47)),
 ('keywords_teenager', np.int64(47)),
 ('keywords_battle', np.int64(46)),
 ('keywords_best friend', np.int64(46)),
 ('keywords_christmas', np.int64(46)),
 ('keywords_hospital', np.int64(46)),
 ('keywords_secret', np.int64(46)),
 ('keywords_vomiting', np.int64(46)),
 ('keywords_cia', np.int64(45)),
 ('keywords_scientist', np.int64(45)),
 ('keywords_singer', np.int64(45)),
 ('keywords_train', np.int64(45)),
 ('keywords_college', np.int64(44)),
 ('keywords_hotel', np.int64(44)),
 ('keywords_future', np.int64(43)),
 ('keywords_fight', np.int64(42)),
 ('keywords_small town', np.int64(42)),
 ('keywords_writer', np.int64(42)),
 ('keywords_terrorist', np.int64(41)),
 ('keywords_texas', np.int64(41))]

In [213]:
for i, col in enumerate(df.columns):
    print(f'{i+1}: {col}')

1: color
2: director_name
3: num_critic_for_reviews
4: duration
5: director_facebook_likes
6: actor_3_facebook_likes
7: actor_2_name
8: actor_1_facebook_likes
9: gross
10: actor_1_name
11: movie_title
12: num_voted_users
13: cast_total_facebook_likes
14: actor_3_name
15: facenumber_in_poster
16: movie_imdb_link
17: num_user_for_reviews
18: budget
19: title_year
20: actor_2_facebook_likes
21: imdb_score
22: aspect_ratio
23: movie_facebook_likes
24: war_symb_title
25: point_symb_title
26: language_Aboriginal
27: language_Arabic
28: language_Aramaic
29: language_Bosnian
30: language_Cantonese
31: language_Chinese
32: language_Czech
33: language_Danish
34: language_Dari
35: language_Dutch
36: language_Dzongkha
37: language_English
38: language_Filipino
39: language_French
40: language_German
41: language_Greek
42: language_Hebrew
43: language_Hindi
44: language_Hungarian
45: language_Icelandic
46: language_Indonesian
47: language_Italian
48: language_Japanese
49: language_Kannada
50: language_Kazakh
51: language_Korean
52: language_Mandarin
53: language_Maya
54: language_Mongolian
55: language_Morse
56: language_Norwegian
57: language_Panjabi
58: language_Persian
59: language_Polish
60: language_Portuguese
61: language_Romanian
62: language_Russian
63: language_Slovenian
64: language_Spanish
65: language_Swahili
66: language_Swedish
67: language_Tamil
68: language_Telugu
69: language_Thai
70: language_Urdu
71: language_Vietnamese
72: language_Zulu
73: country_Argentina
74: country_Aruba
75: country_Australia
76: country_Bahamas
77: country_Belgium
78: country_Brazil
79: country_Bulgaria
80: country_Cambodia
81: country_Cameroon
82: country_Canada
83: country_Chile
84: country_China
85: country_Colombia
86: country_Czech Republic
87: country_Denmark
88: country_Dominican Republic
89: country_Egypt
90: country_English
91: country_Finland
92: country_France
93: country_Georgia
94: country_Germany
95: country_Greece
96: country_Hong Kong
97: country_Hungary
98: country_Iceland
99: country_India
100: country_Indonesia
101: country_Iran
102: country_Ireland
103: country_Israel
104: country_Italy
105: country_Japan
106: country_Kenya
107: country_Kyrgyzstan
108: country_Libya
109: country_Mexico
110: country_Netherlands
111: country_New Line
112: country_New Zealand
113: country_Nigeria
114: country_Norway
115: country_Official site
116: country_Pakistan
117: country_Panama
118: country_Peru
119: country_Philippines
120: country_Poland
121: country_Romania
122: country_Russia
123: country_Slovakia
124: country_Slovenia
125: country_South Africa
126: country_South Korea
127: country_Soviet Union
128: country_Spain
129: country_Sweden
130: country_Switzerland
131: country_Taiwan
132: country_Thailand
133: country_Turkey
134: country_UK
135: country_USA
136: country_United Arab Emirates
137: country_West Germany
138: content_rating_G
139: content_rating_GP
140: content_rating_M
141: content_rating_NC-17
142: content_rating_Not Rated
143: content_rating_PG
144: content_rating_PG-13
145: content_rating_Passed
146: content_rating_R
147: content_rating_TV-14
148: content_rating_TV-G
149: content_rating_TV-MA
150: content_rating_TV-PG
151: content_rating_TV-Y
152: content_rating_TV-Y7
153: content_rating_USA
154: content_rating_Unrated
155: content_rating_X
156: genres_Action
157: genres_Adventure
158: genres_Animation
159: genres_Biography
160: genres_Comedy
161: genres_Crime
162: genres_Documentary
163: genres_Drama
164: genres_Family
165: genres_Fantasy
166: genres_History
167: genres_Horror
168: genres_Music
169: genres_Musical
170: genres_Mystery
171: genres_Romance
172: genres_Sci-Fi
173: genres_Sport
174: genres_Thriller
175: genres_War
176: genres_Other
177: keywords_alien
178: keywords_battle
179: keywords_best friend
180: keywords_box office flop
181: keywords_boy
182: keywords_christmas
183: keywords_cia
184: keywords_college
185: keywords_death
186: keywords_detective
187: keywords_dog
188: keywords_drugs
189: keywords_escape
190: keywords_fbi
191: keywords_female nudity
192: keywords_female protagonist
193: keywords_fight
194: keywords_friend
195: keywords_friendship
196: keywords_future
197: keywords_high school
198: keywords_hospital
199: keywords_hotel
200: keywords_island
201: keywords_lawyer
202: keywords_love
203: keywords_marriage
204: keywords_money
205: keywords_murder
206: keywords_new york city
207: keywords_other
208: keywords_party
209: keywords_police
210: keywords_prison
211: keywords_rescue
212: keywords_revenge
213: keywords_school
214: keywords_scientist
215: keywords_secret
216: keywords_serial killer
217: keywords_sex
218: keywords_singer
219: keywords_small town
220: keywords_teenager
221: keywords_terrorist
222: keywords_texas
223: keywords_train
224: keywords_vegetarian
225: keywords_vomiting
226: keywords_wedding
227: keywords_writer

In [214]:
df.to_pickle("cinemas_cleaned.pkl")